# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
r_binary_packages:
  r-cran-RcppEigen
  r-cran-Rcpp
  r-cran-RcppArmadillo
