# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
apt_packages:
 libnetcdf-dev
 udunits-bin
 libudunits2-dev
 netcdf-bin
 tcl8.5-dev
 tk8.5-dev
 
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
 

before_install:
  - export DISPLAY=:99.0
  - sleep 3
    
language: R
cache: packages
sudo: required

