# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
apt_packages:
 libnetcdf-dev
 udunits-bin
 libudunits2-dev
 netcdf-bin
 tcl8.5-dev
 tk8.5-dev
 
dist: xenial
services:
  - xvfb
 
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
 

before_install:
  - export DISPLAY=:99.0
  - sleep 3
    
language: R
cache: packages
sudo: required

